# Generated by Django 3.2.7 on 2021-09-11 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_name', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('publication', models.CharField(blank=True, max_length=200, null=True)),
                ('short_des', models.CharField(blank=True, max_length=500, null=True)),
                ('buy_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
